//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 02:09:16 PM EST 
//


package com.example.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BugTraceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BugTraceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuildId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AssessmentReportFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InstanceLocation" type="{https://www.swamp.com/com/scarf/struct}InstanceLocationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BugTraceType", propOrder = {
		"buildId",
		"assessmentReportFile",
		"instanceLocation"
})
public class BugTraceType {

	@XmlElement(name = "BuildId")
	protected String buildId;
	@XmlElement(name = "AssessmentReportFile")
	protected String assessmentReportFile;
	@XmlElement(name = "InstanceLocation")
	protected InstanceLocationType instanceLocation;

	/**
	 * Gets the value of the buildId property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getBuildId() {
		return buildId;
	}

	/**
	 * Sets the value of the buildId property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setBuildId(String value) {
		this.buildId = value;
	}

	/**
	 * Gets the value of the assessmentReportFile property.
	 *
	 * @return possible object is
	 * {@link String }
	 */
	public String getAssessmentReportFile() {
		return assessmentReportFile;
	}

	/**
	 * Sets the value of the assessmentReportFile property.
	 *
	 * @param value allowed object is
	 *              {@link String }
	 */
	public void setAssessmentReportFile(String value) {
		this.assessmentReportFile = value;
	}

	/**
	 * Gets the value of the instanceLocation property.
	 *
	 * @return possible object is
	 * {@link InstanceLocationType }
	 */
	public InstanceLocationType getInstanceLocation() {
		return instanceLocation;
	}

	/**
	 * Sets the value of the instanceLocation property.
	 *
	 * @param value allowed object is
	 *              {@link InstanceLocationType }
	 */
	public void setInstanceLocation(InstanceLocationType value) {
		this.instanceLocation = value;
	}

}
