//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.15 at 07:34:01 PM EST 
//


package com.example.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * The root tag AnalyzerReport can have MetricSummaries as a child element. There
 * can be only one occurrence of MetricSummaries, if and only if there is at least one
 * Metric.
 *
 *
 * <p>Java class for MetricSummariesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MetricSummariesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetricSummary" type="{https://www.swamp.com/com/scarf/struct}MetricSummaryType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetricSummariesType", propOrder = {
        "metricSummary"
})
public class MetricSummariesType {

    @XmlElement(name = "MetricSummary", required = true)
    protected List<MetricSummaryType> metricSummary;

    /**
     * Gets the value of the metricSummary property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metricSummary property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetricSummary().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetricSummaryType }
     */
    public List<MetricSummaryType> getMetricSummary() {
        if (metricSummary == null) {
            metricSummary = new ArrayList<MetricSummaryType>();
        }
        return this.metricSummary;
    }

}
